-- Sur Exporta — 06 · Socios de COMCE Sur
-- GENERADO por supabase/build-socios.js. No lo edites a mano: cambia el script y vuelve a generarlo.
-- Requiere haber ejecutado antes 05-tipos-sectores.sql.
-- Las empresas entran como BORRADOR. Si una ya existe (mismo identificador), no se toca.

-- Estados nuevos
insert into estados (clave, nombre) values ('puebla', 'Puebla') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('tlaxcala', 'Tlaxcala') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('veracruz', 'Veracruz') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('campeche', 'Campeche') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('quintana-roo', 'Quintana Roo') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('ciudad-de-mexico', 'Ciudad de México') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('nuevo-leon', 'Nuevo León') on conflict (clave) do update set nombre = excluded.nombre;

-- Certificaciones nuevas
insert into certificaciones (clave, nombre_es, nombre_en, descripcion_es, descripcion_en) values ('cofepris', 'COFEPRIS', 'COFEPRIS', 'Cumplimiento sanitario ante la Comisión Federal para la Protección contra Riesgos Sanitarios.', 'Health compliance with Mexico''s Federal Commission for the Protection against Sanitary Risks.') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en;

-- 23 empresas
insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('calten-group', 'Calten Group', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Logística y comercio exterior para pymes que no cuentan con un departamento de operaciones internacionales.', 'Logistics and foreign trade services for SMEs without an in-house international operations team.', 'Calten Group integra servicios de logística y comercio exterior para pequeñas y medianas empresas. Con más de 18 años de experiencia, ofrece soluciones personalizadas en comercio internacional, transporte, comercialización y auditoría, y acompaña a sus clientes en importación y exportación, cumplimiento, certificaciones IMMEX y PROSEC, capacitación y desarrollo de proveeduría internacional.', 'Calten Group provides integrated logistics and foreign trade services for small and medium-sized companies. With more than 18 years of experience, it offers tailored solutions in international trade, transport, sales and auditing, and supports clients with imports and exports, compliance, IMMEX and PROSEC certification, training and international supplier development.', '18 años de experiencia', '18 years of experience', null, 'sin_dato', null, null, array['Logística internacional', 'Gestión aduanera', 'Coordinación de embarques', 'Consultoría en comercio exterior', 'Certificaciones IMMEX y PROSEC', 'Capacitación', 'Desarrollo de proveeduría internacional']::text[], '{}'::integer[], 'emma.perez@caltengroup.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('cashabroad', 'CashAbroad', null, 'ciudad-de-mexico', null, 'pagos-internacionales', 'Pagos internacionales para empresas mexicanas con cuentas virtuales y dólares digitales.', 'International payments for Mexican companies through virtual accounts and digital dollars.', 'CashAbroad es una startup que facilita los pagos internacionales de empresas mexicanas mediante tecnología blockchain. Su wallet empresarial admite varias stablecoins y permite transferencias empresa–proveedor y cliente–empresa con Estados Unidos, Canadá, Europa, China, Panamá, Colombia y República Dominicana. Abre cuentas virtuales en Estados Unidos en menos de 72 horas, ofrece pagos B2B en dólares digitales las 24 horas con liquidez inmediata en pesos, y opera bajo estándares de cumplimiento del SAT, la UIF, AML, OFAC y FATF.', 'CashAbroad is a start-up that uses blockchain technology to simplify international payments for Mexican companies. Its business wallet supports multiple stablecoins for company-to-supplier and customer-to-company transfers with the United States, Canada, Europe, China, Panama, Colombia and the Dominican Republic. It opens US virtual accounts in under 72 hours, offers 24/7 B2B payments in digital dollars with immediate liquidity in pesos, and operates under SAT, UIF, AML, OFAC and FATF compliance standards.', 'Cuentas en EUA en 72 h', 'US accounts in 72 hours', null, 'sin_dato', null, null, array['Cuentas virtuales en Estados Unidos', 'Pagos B2B en dólares digitales', 'Conversión de divisas y activos digitales', 'Wallet empresarial multi-stablecoin']::text[], '{}'::integer[], 'ruth@cashabroad.one', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('cogne-mexico', 'COGNE México', null, 'tlaxcala', 'Huamantla', 'productos-metalicos', 'Barras y alambres de acero inoxidable y aleaciones especiales para aplicaciones industriales de alta exigencia.', 'Stainless steel and special alloy bars and wire for demanding industrial applications.', 'COGNE México produce y transforma barras y alambres de acero inoxidable y aleaciones especiales. Sus procesos incluyen trefilado, fabricación de barras para válvulas de motores de combustión interna, enderezado y rectificado grueso y fino. Atiende a las industrias automotriz, aeroespacial, médica, petrolera, química, energética y de la construcción.', 'COGNE México produces and processes stainless steel and special alloy bars and wire. Its processes include drawing, manufacturing bars for internal combustion engine valves, straightening, and rough and fine grinding. It serves the automotive, aerospace, medical, oil, chemical, energy and construction industries.', 'Acero inoxidable de precisión', 'Precision stainless steel', null, 'sin_dato', null, null, array['Barras de acero inoxidable', 'Barras para válvulas de motor', 'Alambre para resortes', 'Alambre para forja en frío', 'Perfiles especiales', 'Soldaduras de acero inoxidable']::text[], '{}'::integer[], 'mcastillo@cogne.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('cslogix', 'CsLogix', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Estrategias y soluciones logísticas para comercio internacional y transporte nacional.', 'Logistics strategies and solutions for international trade and domestic transport.', 'CsLogix diseña estrategias y soluciones para operaciones de comercio internacional y logística de transporte nacional. Su trabajo se centra en optimizar procesos, mejorar la coordinación de las cadenas de suministro y facilitar el movimiento eficiente de mercancías, con servicios adaptados a cada cliente.', 'CsLogix designs strategies and solutions for international trade operations and domestic transport logistics. Its work focuses on optimising processes, improving supply chain coordination and moving goods efficiently, with services tailored to each client.', 'Logística nacional e internacional', 'Domestic and international logistics', null, 'sin_dato', null, null, array['Logística internacional', 'Transporte nacional', 'Coordinación de cadena de suministro']::text[], '{}'::integer[], 'nohemi.camberos@cslogix.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('empacabados', 'Empacabados', 'Empacabados S.A. de C.V.', 'puebla', 'Puebla', 'textil-y-confeccion', 'Maquila textil con más de 20 años de experiencia en la confección de prendas de vestir.', 'Apparel contract manufacturer with more than 20 years of experience.', 'Empacabados es una maquiladora textil mexicana con más de 20 años confeccionando prendas de vestir para distintos sectores. Cubre el proceso completo —corte, transfer, sublimado, costura, revisión y empaque— y trabaja para marcas y empresas que buscan manufactura textil confiable.', 'Empacabados is a Mexican apparel contract manufacturer with more than 20 years of experience making garments for different sectors. It covers the whole process — cutting, heat transfer, sublimation, sewing, inspection and packing — for brands and companies looking for reliable textile manufacturing.', '20 años en maquila textil', '20 years in apparel manufacturing', null, 'sin_dato', true, null, array['Confección de prendas', 'Corte', 'Transfer y sublimado', 'Costura', 'Revisión y empaque']::text[], '{}'::integer[], 'maru@empacabados.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('impoexporta', 'ImpoExporta', null, 'quintana-roo', 'Benito Juárez', 'logistica-comercio-exterior', 'Proveedor logístico y asesor en importación y exportación con más de 15 años de experiencia.', 'Logistics provider and import-export adviser with more than 15 years of experience.', 'ImpoExporta (Empresa Importadora de Carga) es un proveedor logístico con más de 15 años de experiencia en operaciones de importación y exportación. Brinda asesoría, consultoría y acompañamiento entre importadores, exportadores y los demás actores de la cadena de comercio internacional, con un lenguaje práctico y soluciones a la medida.', 'ImpoExporta (Empresa Importadora de Carga) is a logistics provider with more than 15 years of experience in import and export operations. It offers advice, consulting and hands-on support between importers, exporters and the other players in the international trade chain, in plain language and with tailored solutions.', '15 años en logística', '15 years in logistics', null, 'sin_dato', null, null, array['Logística de importación y exportación', 'Asesoría en comercio exterior', 'Consultoría']::text[], '{}'::integer[], 'admincun2@impoexporta.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('fairwind-group', 'FairWind Group', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Soluciones de comercio exterior, logística internacional y gestión operativa para crecer en mercados globales.', 'Foreign trade, international logistics and operations management solutions for growing in global markets.', 'FairWind integra servicios de comercio exterior, logística internacional y gestión operativa para empresas que buscan crecer en mercados globales. Con más de 10 años de experiencia, ofrece logística nacional e internacional, consultoría en exportación e importación, búsqueda de proveedores y clientes en el extranjero, gestión aduanera, capacitación y software para controlar operaciones de comercio exterior.', 'FairWind brings together foreign trade, international logistics and operations management services for companies looking to grow in global markets. With more than 10 years of experience, it offers domestic and international logistics, export and import consulting, sourcing of suppliers and customers abroad, customs management, training and software to manage foreign trade operations.', 'Software para comercio exterior', 'Foreign trade software', null, 'sin_dato', null, null, array['Logística nacional e internacional', 'Consultoría en exportación e importación', 'Búsqueda de proveedores y clientes', 'Gestión aduanera', 'Capacitación', 'Software de comercio exterior']::text[], '{}'::integer[], 'jesus.hernandez@fairwind.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('geamex', 'GEAMEX Comercializadora', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Comercializadora poblana que lleva productos mexicanos a mercados nacionales e internacionales.', 'Puebla-based trading company that takes Mexican products to domestic and international markets.', 'GEAMEX Comercializadora, fundada en Puebla en 2014, comercializa productos mexicanos en México y el extranjero e impulsa a las pymes a abrir nuevos mercados. Ofrece asesoría y gestión de comercio exterior, logística internacional, despacho aduanal, planes de negocio y acompañamiento en procesos de internacionalización.', 'GEAMEX Comercializadora, founded in Puebla in 2014, sells Mexican products in Mexico and abroad and helps SMEs open new markets. It offers foreign trade advice and management, international logistics, customs clearance, business plans and support for internationalisation.', 'Comercialización internacional', 'International trading', 2014, 'sin_dato', null, null, array['Comercialización internacional', 'Asesoría en comercio exterior', 'Logística internacional', 'Despacho aduanal', 'Planes de negocio e internacionalización']::text[], '{}'::integer[], 'anaid@geamex.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('amp-solutions', 'AMP Solutions', null, 'ciudad-de-mexico', null, 'logistica-comercio-exterior', 'Logística integral, segura y personalizada a lo largo de toda la cadena de suministro.', 'Safe, tailored end-to-end logistics across the whole supply chain.', 'AMP Solutions ofrece soluciones logísticas integrales, seguras y personalizadas para toda la cadena de suministro. Apoya a empresas de distintos sectores en la coordinación, distribución y gestión logística, con atención cercana y operaciones adaptadas a cada cliente.', 'AMP Solutions provides safe, tailored end-to-end logistics solutions across the supply chain. It supports companies in different sectors with coordination, distribution and logistics management, with close attention and operations adapted to each client.', 'Logística integral', 'End-to-end logistics', null, 'sin_dato', null, null, array['Logística integral', 'Distribución', 'Gestión de cadena de suministro']::text[], '{}'::integer[], 'rcareaga@grupoamp.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('grupo-ravara', 'Grupo RAVARA', null, 'nuevo-leon', 'García', 'cosmetica', 'Centro tecnológico que diseña y fabrica ingredientes activos para cosmética y cuidado personal.', 'Technology centre that designs and manufactures active ingredients for cosmetics and personal care.', 'Grupo RAVARA es un centro tecnológico mexicano que diseña y manufactura ingredientes activos para las industrias cosmética, de cuidado personal, del hogar y capilar. Combina ciencia y herbolaria tradicional para desarrollar extractos botánicos, proteínas, péptidos y complejos activos con funciones de hidratación, antienvejecimiento, protección capilar, regeneración celular, control antimicrobiano y protección contra la contaminación.', 'Grupo RAVARA is a Mexican technology centre that designs and manufactures active ingredients for the cosmetics, personal care, home care and hair care industries. It combines science with traditional herbal knowledge to develop botanical extracts, proteins, peptides and active complexes for hydration, anti-ageing, hair protection, cell renewal, antimicrobial control and protection against pollution.', 'Ingredientes de origen natural', 'Naturally derived ingredients', null, 'sin_dato', null, null, array['Extractos botánicos', 'Proteínas y péptidos', 'Complejos activos', 'Activos para cuidado capilar', 'Formulaciones a la medida']::text[], '{}'::integer[], 'alejandra@gruporavara.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('lari-moda', 'LARI MODA', null, 'oaxaca', null, 'textil-y-confeccion', 'Prendas bordadas a mano por mujeres artesanas, con telas y procesos conscientes.', 'Garments hand-embroidered by women artisans, using mindful fabrics and processes.', 'LARI MODA crea prendas bordadas a mano por mujeres artesanas en pequeños talleres comunitarios, con telas más amigables con la naturaleza. Su modelo impulsa el empoderamiento económico de las mujeres, preserva técnicas tradicionales de bordado y promueve una moda ética, con piezas atemporales pensadas para durar.', 'LARI MODA makes garments hand-embroidered by women artisans in small community workshops, using more environmentally friendly fabrics. Its model supports women''s economic empowerment, preserves traditional embroidery techniques and promotes ethical fashion, with timeless pieces made to last.', 'Bordado artesanal', 'Hand embroidery', null, 'sin_dato', null, null, array['Prendas bordadas a mano', 'Moda sostenible']::text[], '{}'::integer[], 'oly@larimoda.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('licorera-del-sur', 'Licorera del Sur', null, 'oaxaca', 'Santiago Matatlán', 'bebidas-espirituosas', 'Productora y distribuidora de bebidas espirituosas de Santiago Matatlán, Oaxaca, con más de 40 años de experiencia.', 'Spirits producer and distributor from Santiago Matatlán, Oaxaca, with more than 40 years of experience.', 'Licorera del Sur produce y distribuye bebidas espirituosas desde Santiago Matatlán, Oaxaca, una de las regiones con mayor tradición mezcalera del país. Con más de 40 años de experiencia y productos galardonados, cuenta con capacidad propia de fabricación, embotellado, etiquetado y distribución.', 'Licorera del Sur produces and distributes spirits from Santiago Matatlán, Oaxaca, one of Mexico''s most traditional mezcal regions. With more than 40 years of experience and award-winning products, it has its own production, bottling, labelling and distribution capacity.', '40 años de trayectoria', '40 years in business', null, 'sin_dato', null, null, array['Bebidas espirituosas']::text[], '{}'::integer[], 'jrodriguez@licoreradelsur.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('mezcal-capotlan', 'Mezcal Capotlán', null, 'oaxaca', 'Las Razas', 'destilados-de-agave', 'Mezcal artesanal oaxaqueño de agaves Espadín, Tobalá y Tepeztate.', 'Artisanal mezcal from Oaxaca made from Espadín, Tobalá and Tepeztate agaves.', 'Mezcal Capotlán elabora y promueve mezcal artesanal de alta calidad con métodos tradicionales de producción. Sus destilados expresan el carácter de cada variedad de agave —Espadín, Tobalá y Tepeztate— y la riqueza cultural, los aromas y sabores de Oaxaca.', 'Mezcal Capotlán makes and promotes high-quality artisanal mezcal using traditional production methods. Its spirits express the character of each agave variety — Espadín, Tobalá and Tepeztate — and the cultural richness, aromas and flavours of Oaxaca.', 'Mezcal artesanal', 'Artisanal mezcal', null, 'sin_dato', null, null, array['Espadín', 'Tobalá', 'Tepeztate']::text[], '{}'::integer[], 'mezcalcapotlan@gmail.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('mezcal-dolores', 'Mezcal Dolores', null, 'oaxaca', 'Santiago Matatlán', 'destilados-de-agave', 'Mezcal artesanal de Santiago Matatlán elaborado con procesos tradicionales.', 'Artisanal mezcal from Santiago Matatlán made with traditional processes.', 'Mezcal Dolores produce y comercializa mezcal artesanal cuidando cada etapa del proceso tradicional, para ofrecer destilados auténticos, con identidad y carácter propio, dirigidos al mercado nacional e internacional.', 'Mezcal Dolores produces and sells artisanal mezcal, taking care of every stage of the traditional process to offer authentic spirits with their own identity and character for domestic and international markets.', 'Mezcal artesanal', 'Artisanal mezcal', null, 'sin_dato', null, null, array['Mezcal artesanal']::text[], '{}'::integer[], 'marilyn.dolores30@gmail.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('mezcal-la-entrega', 'Mezcal La Entrega', null, 'oaxaca', 'Oaxaca de Juárez', 'destilados-de-agave', 'Mezcal artesanal 100% orgánico, destilado en alambique de cobre.', '100% organic artisanal mezcal distilled in copper stills.', 'Mezcal La Entrega produce mezcal artesanal 100% orgánico con procesos tradicionales: agaves maduros cocidos en hornos de piedra subterráneos, fermentación natural en tinas de madera y destilación en alambique de cobre. El resultado es un destilado puro, complejo y con el ahumado característico del mezcal.', 'Mezcal La Entrega produces 100% organic artisanal mezcal using traditional methods: mature agaves cooked in underground stone ovens, natural fermentation in wooden vats and distillation in copper stills. The result is a pure, complex spirit with mezcal''s characteristic smokiness.', '100% orgánico', '100% organic', null, 'sin_dato', null, null, array['Mezcal artesanal orgánico']::text[], '{}'::integer[], 'laentregamezcal@gmail.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('multilog-internacional', 'Multilog Internacional', null, 'ciudad-de-mexico', null, 'logistica-comercio-exterior', 'Logística y cadena de suministro: transporte terrestre, aéreo y marítimo, almacenaje y distribución.', 'Logistics and supply chain: road, air and sea freight, warehousing and distribution.', 'Multilog Internacional ofrece desde hace más de 16 años soluciones integrales de logística y cadena de suministro para empresas de distintos sectores. Integra transporte terrestre, aéreo y marítimo, almacenamiento, distribución y operaciones in-house bajo un mismo esquema, con atención personalizada.', 'For more than 16 years, Multilog Internacional has provided end-to-end logistics and supply chain solutions for companies in different sectors. It combines road, air and sea freight, warehousing, distribution and in-house operations under a single scheme, with personalised service.', '16 años en logística', '16 years in logistics', null, 'sin_dato', null, null, array['Transporte terrestre', 'Transporte aéreo', 'Transporte marítimo', 'Almacenamiento', 'Distribución', 'Operaciones in-house']::text[], '{}'::integer[], 'orlando.vazquez@multilog.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('oceamar', 'Oceamar', null, 'campeche', 'Ciudad del Carmen', 'logistica-comercio-exterior', 'Agencia de logística offshore para la industria marítima y petrolera.', 'Offshore logistics agency for the maritime and oil industries.', 'Oceamar (Ocean Marine) es una agencia de logística integral offshore que atiende a la industria marítima y petrolera. Coordina soluciones logísticas, operativas y de soporte para operaciones costa afuera, con foco en eficiencia, seguridad y cumplimiento en proyectos del sector energético.', 'Oceamar (Ocean Marine) is an end-to-end offshore logistics agency serving the maritime and oil industries. It coordinates logistics, operational and support solutions for offshore operations, focusing on efficiency, safety and compliance in energy sector projects.', 'Logística offshore', 'Offshore logistics', null, 'sin_dato', null, null, array['Logística offshore', 'Soporte a operaciones costa afuera', 'Servicios a la industria marítima y petrolera']::text[], '{}'::integer[], 'enrique.escobar@oceamar.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('pilu-uniformes', 'Pilu Uniformes', null, 'puebla', 'Puebla', 'textil-y-confeccion', 'Diseño y fabricación de uniformes industriales e institucionales.', 'Design and manufacture of industrial and corporate uniforms.', 'Pilu Uniformes Industriales de México diseña, fabrica y comercializa uniformes industriales e institucionales adaptados a cada organización. Combina imagen corporativa, ergonomía y seguridad en prendas funcionales y de alta calidad.', 'Pilu Uniformes Industriales de México designs, manufactures and sells industrial and corporate uniforms tailored to each organisation. It combines corporate image, ergonomics and safety in functional, high-quality garments.', 'Uniformes a la medida', 'Made-to-order uniforms', null, 'sin_dato', null, null, array['Uniformes industriales', 'Uniformes institucionales']::text[], '{}'::integer[], 'eduardosanchez@piluniformes.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('las-vegas-premium-limes', 'Las Vegas Premium Limes', 'Productos Men-Frut S.A. de C.V.', 'veracruz', 'Martínez de la Torre', 'frutas-y-hortalizas', 'Empaque y exportación de lima persa de alta calidad durante todo el año.', 'Packing and export of high-quality Persian limes all year round.', 'Productos Men-Frut empaca y exporta lima persa bajo la marca Las Vegas Premium Limes desde Martínez de la Torre, Veracruz, una de las regiones citrícolas más importantes de México. Ofrece producto fresco todo el año y cumple estándares internacionales para abastecer mercados alrededor del mundo.', 'Productos Men-Frut packs and exports Persian limes under the Las Vegas Premium Limes brand from Martínez de la Torre, Veracruz, one of Mexico''s leading citrus regions. It supplies fresh product all year round and meets international standards to serve markets around the world.', 'Lima persa todo el año', 'Persian limes all year round', null, 'exportando', null, null, array['Lima persa']::text[], '{}'::integer[], 'hugo.mendez@citru-mex.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('recodding', 'Recodding', null, 'puebla', 'Puebla', 'tecnologia', 'Transformación digital: inteligencia de negocios, automatización y ERP Odoo.', 'Digital transformation: business intelligence, automation and Odoo ERP.', 'Recodding acompaña a las empresas en su transformación digital para hacerlas más rentables y eficientes. Combina automatización, análisis de datos e integración tecnológica: Business Intelligence, automatización de procesos, implementación de ERP Odoo, arquitectura en la nube e integración de bases de datos.', 'Recodding supports companies through digital transformation to make them more profitable and efficient. It combines automation, data analysis and technology integration: business intelligence, process automation, Odoo ERP implementation, cloud architecture and database integration.', 'Implementación de Odoo', 'Odoo implementation', null, 'sin_dato', null, null, array['Business Intelligence', 'Automatización de procesos', 'Implementación de ERP Odoo', 'Arquitectura en la nube', 'Integración de bases de datos']::text[], '{}'::integer[], 'eduardo@recodding.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('saeta', 'Saeta Consulting', null, 'puebla', 'Puebla', 'consultoria', 'Consultoría empresarial que simplifica los procesos corporativos.', 'Business consulting that simplifies corporate processes.', 'Saeta es una firma de consultoría empresarial que ofrece soluciones estratégicas y personalizadas para el crecimiento de las organizaciones. Trabaja como un aliado cercano para facilitar la toma de decisiones y hacer los procesos corporativos más claros, eficientes y transparentes.', 'Saeta is a business consulting firm offering strategic, tailored solutions for organisational growth. It works as a close partner to support decision-making and make corporate processes clearer, more efficient and more transparent.', 'Orientación corporativa', 'Corporate guidance', null, 'sin_dato', null, null, array['Consultoría empresarial', 'Estrategia', 'Mejora de procesos']::text[], '{}'::integer[], 'eduardo.lopez@saetaoc.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('solferino-native', 'Solferino Native', null, 'quintana-roo', 'Solferino', 'bebidas-espirituosas', 'Primera destilería de Quintana Roo: gin artesanal con botánicos de la selva maya, medalla de oro como Mejor Gin de México en los World Gin Awards 2025.', 'Quintana Roo''s first distillery: craft gin with Mayan jungle botanicals, awarded gold as Best Mexican Gin at the World Gin Awards 2025.', 'Solferino Native es la primera destilería de Quintana Roo. Nació en 2020 en Solferino, un poblado de la selva maya camino a Holbox, y elabora gin y licores artesanales en alambique de cobre, en microlotes de máximo 120 botellas. Sus botánicos —zacate limón, hierbabuena, hoja santa, pimienta negra, romero y piel de toronja— se recolectan frescos con los vecinos del pueblo y se suman al enebro, el regaliz y la canela, sin químicos ni conservadores.

Su Dry Gin ganó la medalla de oro como Mejor Gin de México en los World Gin Awards 2025, en Reino Unido, donde quedó entre los seis mejores del mundo en la categoría Contemporary Style, y volvió a ser reconocido en la edición 2026. Suma oro en Cata d''Or World Spirits Awards (Chile, 2021 y 2025), plata en Las Vegas Global Spirit Awards 2025 y Gran Oro en el Concurso de Espirituosos de Guanajuato, y es miembro de The Gin Guild de Londres. Se vende en Quintana Roo, Ciudad de México, Estado de México, Querétaro y Baja California, en las tiendas La Europea de todo el país y en Amazon y Mercado Libre.', 'Solferino Native is Quintana Roo''s first distillery. It was founded in 2020 in Solferino, a village in the Mayan jungle on the way to Holbox, and makes craft gin and liqueurs in copper stills, in micro-batches of no more than 120 bottles. Its botanicals — lemongrass, spearmint, hoja santa, black pepper, rosemary and grapefruit peel — are gathered fresh with local villagers and added to juniper, liquorice and cinnamon, with no chemicals or preservatives.

Its Dry Gin won gold as Best Mexican Gin at the World Gin Awards 2025 in the United Kingdom, where it ranked among the world''s top six in the Contemporary Style category, and was recognised again in the 2026 edition. It also holds gold at the Cata d''Or World Spirits Awards (Chile, 2021 and 2025), silver at the Las Vegas Global Spirit Awards 2025 and Grand Gold at the Guanajuato Spirits Competition, and is a member of The Gin Guild in London. It is sold in Quintana Roo, Mexico City, the State of Mexico, Querétaro and Baja California, in La Europea stores nationwide, and on Amazon and Mercado Libre.', 'Oro · World Gin Awards 2025', 'Gold · World Gin Awards 2025', null, 'sin_dato', null, '30–55%', array['Solferino Native Dry Gin · 40% Alc. · 750 ml', 'Solferino Native Overproof Edition · gin 55% Alc.', 'Solferino Native Flair Edition · gin para bartenders de flair', 'Solferino Native Absenta · 55% Alc.', 'Balam · licor cítrico de zacate limón, naranja y toronja', 'Pancheel · licor de yaka · 30% Alc.']::text[], array[750]::integer[], 'info@solferinogin.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('toke-innova', 'Toke Innova', null, 'puebla', 'Puebla', 'alimentos-procesados', 'Salsa macha, chimichurri, especias y productos artesanales de Puebla, 100% naturales, con venta en 12 estados de México y cuatro de Estados Unidos.', 'Artisanal salsa macha, chimichurri, spices and pantry products from Puebla — 100% natural, sold in 12 Mexican states and four US states.', 'Toke Innova, fundada en Puebla en 2017, elabora productos artesanales mexicanos 100% naturales bajo sus marcas La Artesanal Herencia Orza® y ¡Ay Buey!®. Empezó con su Salsa Macha y hoy su catálogo reúne 24 presentaciones: salsa macha en cuatro variedades, chimichurri, chiles y especias, miel, perlas de tapioca, crema de cacahuate y galletas.

Vende en 12 estados de México y en Estados Unidos, donde tiene presencia en California, Kansas, Oklahoma y Texas; sus etiquetas ya vienen en inglés y francés. Cuenta con registro ante COFEPRIS y la FDA. Sus productos tienen una vida de anaquel de 6 meses a 3 años y se surten en cajas de 8 a 52 piezas, según la presentación.', 'Toke Innova, founded in Puebla in 2017, makes 100% natural artisanal Mexican products under its La Artesanal Herencia Orza® and ¡Ay Buey!® brands. It started with its Salsa Macha and its catalogue now includes 24 products: salsa macha in four varieties, chimichurri, chillies and spices, honey, tapioca pearls, peanut butter and cookies.

It sells in 12 Mexican states and in the United States, with presence in California, Kansas, Oklahoma and Texas, and its labels are already in English and French. It is registered with COFEPRIS and the FDA. Shelf life ranges from 6 months to 3 years, and products ship in cases of 8 to 52 units depending on the item.', 'Vende en 4 estados de EUA', 'Sold in 4 US states', null, 'exportando', null, null, array['Salsa Macha 4 chiles y 6 semillas · 200 g', 'Salsa Macha 3 chiles y 3 semillas · 80 g', 'Salsa Macha de cacahuate con chile morita · 200 g y 80 g', 'Salsa Macha de miel de abeja y arándanos · 200 g y 80 g', 'Salsa No Tan Macha · 200 g y 80 g', 'Chimichurri · 200 g y 80 g', 'Chimichurri picoso · 80 g', 'Chile quebrado · 150 g', 'Pimienta de cayena · 60 g', 'Paprika · 60 g', 'Ajonjolí negro · 75 g', 'Miel pura de abeja · 100 g', 'Perlas de miel con propóleo · 80 g', 'Perlas de tapioca · 250 g y 500 g', 'Crema de cacahuate · 340 g', 'Galletas artesanales (nuez con amaranto, arándanos, avena, avellana) · 100 g']::text[], '{}'::integer[], 'aortiz.ventas@tokeinnova.com', '+52 222 801 7636', 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'toke-innova' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'toke-innova' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'cofepris' from empresas where slug = 'toke-innova' on conflict do nothing;

-- Después de revisarlas en el panel, para publicar todas de una vez:
-- update empresas set estatus = 'publicado' where fuente = 'Directorio de Socios COMCE Sur 2026' and estatus = 'borrador';
