-- Sur Exporta — 06 · Socios de COMCE Sur
-- GENERADO por supabase/build-socios.js. No lo edites a mano: cambia el script y vuelve a generarlo.
-- Requiere haber ejecutado antes 05-tipos-sectores.sql.
-- Las empresas entran como BORRADOR. Si una ya existe (mismo identificador), no se toca.

-- Estados nuevos
insert into estados (clave, nombre) values ('puebla', 'Puebla') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('tlaxcala', 'Tlaxcala') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('veracruz', 'Veracruz') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('campeche', 'Campeche') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('quintana-roo', 'Quintana Roo') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('ciudad-de-mexico', 'Ciudad de México') on conflict (clave) do update set nombre = excluded.nombre;
insert into estados (clave, nombre) values ('nuevo-leon', 'Nuevo León') on conflict (clave) do update set nombre = excluded.nombre;

-- Certificaciones nuevas
insert into certificaciones (clave, nombre_es, nombre_en, descripcion_es, descripcion_en) values ('cofepris', 'COFEPRIS', 'COFEPRIS', 'Cumplimiento sanitario ante la Comisión Federal para la Protección contra Riesgos Sanitarios.', 'Health compliance with Mexico''s Federal Commission for the Protection against Sanitary Risks.') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en;

-- 23 empresas
insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('calten-group', 'Calten Group', null, 'puebla', 'San Pedro Cholula', 'logistica-comercio-exterior', 'Logística, comercio exterior e inspección en origen para pymes que no tienen un departamento de operaciones internacionales.', 'Logistics, foreign trade and inspection at origin for SMEs without an in-house international operations team.', 'Calten Group acompaña a pequeñas y medianas empresas que importan o exportan sin tener un departamento de operaciones internacionales. Con más de 18 años de experiencia, integra logística internacional, gestión aduanera, transporte nacional y coordinación de embarques, ya sea por operación o como equipo in-house por contrato, y actúa también como comercializadora.

En comercio exterior arma y revisa expedientes, gestiona trámites ante la VUCEM, asesora en importación y exportación, en el cumplimiento de NOMs y en certificaciones IMMEX y PROSEC, y ayuda a calcular el costo y precio de productos internacionales. Además ofrece inspección en origen —auditoría de fábrica, control de calidad e inspección previa al embarque—, seguros de carga nacional e internacional y cursos de comercio exterior, básicos o a la medida.', 'Calten Group supports small and medium-sized companies that import or export without an international operations department. With more than 18 years of experience, it combines international logistics, customs management, domestic transport and shipment coordination — per operation or as an in-house team on a time-based contract — and also acts as a trading company.

In foreign trade, it prepares and reviews compliance files, handles procedures on Mexico''s VUCEM single window, advises on imports and exports, Mexican Official Standards (NOMs) and IMMEX and PROSEC certification, and helps cost and price international products. It also offers inspection at origin — factory audits, quality control and pre-shipment inspection — domestic and international cargo insurance, and foreign trade courses, from basics to custom programmes.', 'Inspección de calidad en origen', 'Quality inspection at origin', null, 'sin_dato', null, null, array['Logística internacional y transporte nacional', 'Gestión aduanera', 'Coordinación de embarques (por operación o in-house)', 'Expedientes de comercio exterior y trámites VUCEM', 'Certificaciones IMMEX y PROSEC', 'Asesoría en NOMs', 'Costeo y pricing de productos internacionales', 'Inspección en origen: auditoría de fábrica y control de calidad', 'Seguros de carga nacional e internacional', 'Cursos de comercio exterior']::text[], '{}'::integer[], 'emma.perez@caltengroup.com', '+52 222 455 3621', 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('cashabroad', 'CashAbroad', null, 'ciudad-de-mexico', null, 'pagos-internacionales', 'Pagos a proveedores internacionales con dólares digitales (USDC) para exportadores e importadores que operan entre México, Estados Unidos y China.', 'Supplier payments abroad with digital dollars (USDC) for exporters and importers trading between Mexico, the United States and China.', 'CashAbroad es una plataforma de tesorería empresarial para exportadores e importadores que operan entre México, Estados Unidos y China. Con una cuenta en dólares digitales (USDC, con paridad 1:1 con el dólar), las empresas pagan a proveedores y reciben cobros de clientes en el extranjero en unas cuatro horas —en lugar de los días que toma una transferencia tradicional—, deciden cuándo convertir y liquidan en moneda local mediante socios bancarios en más de ocho países.

La cuenta se activa en menos de 48 horas, no cobra anualidad y funciona junto a las cuentas bancarias que la empresa ya usa. Opera sobre las blockchains Stellar y Starknet, con procesos KYB/KYC, prevención de lavado de dinero y monitoreo de transacciones alineados con los requisitos del SAT para actividades vulnerables, y ofrece acompañamiento para configurar cada flujo (Business Concierge). Cuenta con el respaldo de Techstars y Draper University.', 'CashAbroad is a corporate treasury platform for exporters and importers trading between Mexico, the United States and China. With an account in digital dollars (USDC, pegged 1:1 to the US dollar), companies pay suppliers and collect from customers abroad in about four hours — instead of the days a traditional wire takes — decide when to convert, and settle in local currency through banking partners in more than eight countries.

Accounts are activated in under 48 hours, with no annual fee, and work alongside the bank accounts a company already uses. It runs on the Stellar and Starknet blockchains, with KYB/KYC, anti-money-laundering and transaction-monitoring processes aligned with Mexican tax authority (SAT) requirements for vulnerable activities, and offers hands-on support to set up each flow (Business Concierge). It is backed by Techstars and Draper University.', 'Pagos internacionales en 4 horas', 'International payments in 4 hours', null, 'sin_dato', null, null, array['Cuenta empresarial en dólares digitales (USDC)', 'Pagos a proveedores en México, Estados Unidos y China', 'Cobros de clientes en el extranjero', 'Conversión a moneda local y salida bancaria en más de 8 países', 'Tesorería con stablecoins', 'Business Concierge: configuración de flujos financieros']::text[], '{}'::integer[], 'ruth@cashabroad.one', '+52 55 8046 5994', 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('cogne-mexico', 'COGNE México', null, 'tlaxcala', 'Huamantla', 'productos-metalicos', 'Alambre y barras de acero inoxidable y aleaciones de níquel fabricados en Huamantla, Tlaxcala, por la planta mexicana del grupo italiano Cogne. Exporta a Estados Unidos y Europa.', 'Stainless steel and nickel alloy wire and bars made in Huamantla, Tlaxcala, by the Mexican plant of Italy''s Cogne Group. Exports to the United States and Europe.', 'COGNE México —antes Trefilados Inoxidables de México (TIM)— es la planta mexicana del grupo Cogne Acciai Speciali, con sede en Aosta, Italia, y más de un siglo de historia, líder mundial en productos largos de acero inoxidable y aleaciones de níquel. Su planta en la Ciudad Industrial Xicohténcatl II de Huamantla, Tlaxcala, ocupa un terreno de 36,500 m² con 13,000 m² de naves, oficinas y laboratorios, y cuenta con certificaciones ISO 9001, IATF 16949 para la industria automotriz, ISO 14001 e Industria Limpia.

Fabrica alambre de acero inoxidable y de aleaciones de níquel de 0.15 a 10 mm —fino, para resortes, para forja en frío, planos y perfiles especiales— en rollos, botes y carretes; barras de acero inoxidable de 3 a 20 mm y barras rectificadas sin centros de 6 a 31.5 mm, con maquila de rectificado desde una tonelada e inspección por corrientes de Eddy y ultrasonido. También ofrece soldaduras especiales de acero inoxidable, níquel y aluminio, y acero para válvulas automotrices. Exporta a Estados Unidos, Europa y Centro y Sudamérica, y opera con los programas IMMEX, ALTEX y PROSEC y como Operador Económico Autorizado.', 'COGNE México — formerly Trefilados Inoxidables de México (TIM) — is the Mexican plant of the Cogne Acciai Speciali group, headquartered in Aosta, Italy, with more than a century of history and a world leader in long stainless steel and nickel alloy products. Its plant in the Xicohténcatl II Industrial City in Huamantla, Tlaxcala, sits on a 36,500 m² site with 13,000 m² of production halls, offices and laboratories, and is certified to ISO 9001, IATF 16949 for the automotive industry, ISO 14001 and Mexico''s Clean Industry programme.

It makes stainless steel and nickel alloy wire from 0.15 to 10 mm — fine, spring, cold-heading, flat and special-profile wire — on coils, drums and spools; stainless steel bars from 3 to 20 mm and centreless-ground bars from 6 to 31.5 mm, with toll grinding from one tonne and eddy-current and ultrasonic inspection. It also supplies special stainless steel, nickel and aluminium welding wire, and automotive valve steel. It exports to the United States, Europe and Central and South America, and operates under Mexico''s IMMEX, ALTEX and PROSEC programmes and as an Authorised Economic Operator.', 'Planta del grupo italiano Cogne', 'Plant of Italy''s Cogne Group', null, 'exportando', null, null, array['Alambre de acero inoxidable de 0.15 a 10 mm', 'Alambre de aleaciones de níquel', 'Alambre para resortes', 'Alambre para forja en frío', 'Alambres planos y perfiles especiales', 'Barras de acero inoxidable de 3 a 20 mm', 'Barras rectificadas sin centros (6 a 31.5 mm)', 'Maquila de rectificado desde 1 tonelada', 'Soldaduras especiales de inoxidable, níquel y aluminio', 'Acero para válvulas automotrices']::text[], '{}'::integer[], 'mcastillo@cogne.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'cogne-mexico' on conflict do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('cslogix', 'CsLogix', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Estrategias y soluciones logísticas para comercio internacional y transporte nacional.', 'Logistics strategies and solutions for international trade and domestic transport.', 'CsLogix diseña estrategias y soluciones para operaciones de comercio internacional y logística de transporte nacional. Su trabajo se centra en optimizar procesos, mejorar la coordinación de las cadenas de suministro y facilitar el movimiento eficiente de mercancías, con servicios adaptados a cada cliente.', 'CsLogix designs strategies and solutions for international trade operations and domestic transport logistics. Its work focuses on optimising processes, improving supply chain coordination and moving goods efficiently, with services tailored to each client.', 'Logística nacional e internacional', 'Domestic and international logistics', null, 'sin_dato', null, null, array['Logística internacional', 'Transporte nacional', 'Coordinación de cadena de suministro']::text[], '{}'::integer[], 'nohemi.camberos@cslogix.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('empacabados', 'Empacabados', 'Empacabados S.A. de C.V.', 'puebla', 'Puebla', 'textil-y-confeccion', 'Maquila textil con más de 20 años de experiencia en la confección de prendas de vestir.', 'Apparel contract manufacturer with more than 20 years of experience.', 'Empacabados es una maquiladora textil mexicana con más de 20 años confeccionando prendas de vestir para distintos sectores. Cubre el proceso completo —corte, transfer, sublimado, costura, revisión y empaque— y trabaja para marcas y empresas que buscan manufactura textil confiable.', 'Empacabados is a Mexican apparel contract manufacturer with more than 20 years of experience making garments for different sectors. It covers the whole process — cutting, heat transfer, sublimation, sewing, inspection and packing — for brands and companies looking for reliable textile manufacturing.', '20 años en maquila textil', '20 years in apparel manufacturing', null, 'sin_dato', true, null, array['Confección de prendas', 'Corte', 'Transfer y sublimado', 'Costura', 'Revisión y empaque']::text[], '{}'::integer[], 'maru@empacabados.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('impoexporta', 'ImpoExporta', null, 'quintana-roo', 'Benito Juárez', 'logistica-comercio-exterior', 'Proveedor logístico y asesor en importación y exportación con más de 15 años de experiencia.', 'Logistics provider and import-export adviser with more than 15 years of experience.', 'ImpoExporta (Empresa Importadora de Carga) es un proveedor logístico con más de 15 años de experiencia en operaciones de importación y exportación. Brinda asesoría, consultoría y acompañamiento entre importadores, exportadores y los demás actores de la cadena de comercio internacional, con un lenguaje práctico y soluciones a la medida.', 'ImpoExporta (Empresa Importadora de Carga) is a logistics provider with more than 15 years of experience in import and export operations. It offers advice, consulting and hands-on support between importers, exporters and the other players in the international trade chain, in plain language and with tailored solutions.', '15 años en logística', '15 years in logistics', null, 'sin_dato', null, null, array['Logística de importación y exportación', 'Asesoría en comercio exterior', 'Consultoría']::text[], '{}'::integer[], 'admincun2@impoexporta.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('fairwind-group', 'FairWind Group', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Soluciones de comercio exterior, logística internacional y gestión operativa para crecer en mercados globales.', 'Foreign trade, international logistics and operations management solutions for growing in global markets.', 'FairWind integra servicios de comercio exterior, logística internacional y gestión operativa para empresas que buscan crecer en mercados globales. Con más de 10 años de experiencia, ofrece logística nacional e internacional, consultoría en exportación e importación, búsqueda de proveedores y clientes en el extranjero, gestión aduanera, capacitación y software para controlar operaciones de comercio exterior.', 'FairWind brings together foreign trade, international logistics and operations management services for companies looking to grow in global markets. With more than 10 years of experience, it offers domestic and international logistics, export and import consulting, sourcing of suppliers and customers abroad, customs management, training and software to manage foreign trade operations.', 'Software para comercio exterior', 'Foreign trade software', null, 'sin_dato', null, null, array['Logística nacional e internacional', 'Consultoría en exportación e importación', 'Búsqueda de proveedores y clientes', 'Gestión aduanera', 'Capacitación', 'Software de comercio exterior']::text[], '{}'::integer[], 'jesus.hernandez@fairwind.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('geamex', 'GEAMEX Comercializadora', null, 'puebla', 'Puebla', 'logistica-comercio-exterior', 'Comercializadora poblana que lleva productos mexicanos a mercados nacionales e internacionales.', 'Puebla-based trading company that takes Mexican products to domestic and international markets.', 'GEAMEX Comercializadora, fundada en Puebla en 2014, comercializa productos mexicanos en México y el extranjero e impulsa a las pymes a abrir nuevos mercados. Ofrece asesoría y gestión de comercio exterior, logística internacional, despacho aduanal, planes de negocio y acompañamiento en procesos de internacionalización.', 'GEAMEX Comercializadora, founded in Puebla in 2014, sells Mexican products in Mexico and abroad and helps SMEs open new markets. It offers foreign trade advice and management, international logistics, customs clearance, business plans and support for internationalisation.', 'Comercialización internacional', 'International trading', 2014, 'sin_dato', null, null, array['Comercialización internacional', 'Asesoría en comercio exterior', 'Logística internacional', 'Despacho aduanal', 'Planes de negocio e internacionalización']::text[], '{}'::integer[], 'anaid@geamex.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('amp-solutions', 'Grupo AMP Solutions', null, 'ciudad-de-mexico', 'Cuauhtémoc', 'logistica-comercio-exterior', 'Logística integral y asesoría en comercio exterior: despacho aduanal, fletes marítimo y terrestre, almacenaje y Recinto Fiscalizado Estratégico (RFE).', 'End-to-end logistics and foreign trade advice: customs clearance, sea and road freight, warehousing and Strategic Bonded Zone (RFE) services.', 'Grupo AMP Solutions integra en un solo servicio la cadena logística de importación y exportación: flete marítimo y terrestre, despacho aduanal, almacenaje, maniobras y seguro de mercancías. Trabaja con agentes aduanales aliados en las principales aduanas del país —Manzanillo, Lázaro Cárdenas, Veracruz, el AICM, Pantaco y el Aeropuerto de Guadalajara— y maneja alrededor de 250 despachos al mes y 75,000 toneladas de carga al año.

Mueve contenedor completo (FCL), carga consolidada (LCL), refrigerada, de proyecto, sobredimensionada y mercancía peligrosa, con unidades con rastreo GPS las 24 horas y custodia en carretera. Cuenta con 1,500 m² de almacén techado y 4,200 m² de bodega con vigilancia por circuito cerrado, y ofrece Recinto Fiscalizado Estratégico (RFE), depósito fiscal, oficina IMMEX, certificación de IVA e IEPS y clasificación arancelaria. Atiende sobre todo a las industrias de maquinaria pesada, acero, automotriz, equipo médico, química, calzado, textil y electrónica.', 'Grupo AMP Solutions brings the whole import and export logistics chain into a single service: sea and road freight, customs clearance, warehousing, cargo handling and cargo insurance. It works with partner customs brokers at Mexico''s main customs points — Manzanillo, Lázaro Cárdenas, Veracruz, Mexico City International Airport, Pantaco and Guadalajara Airport — and handles around 250 customs clearances a month and 75,000 tonnes of cargo a year.

It moves full container loads (FCL), less-than-container loads (LCL), refrigerated, project, oversized and dangerous cargo, with 24/7 GPS-tracked trucks and road escort. It has 1,500 m² of covered warehouse and 4,200 m² of storage with CCTV surveillance, and offers Strategic Bonded Zone (RFE) and bonded warehouse services, an IMMEX office, VAT and IEPS certification, and tariff classification. It mainly serves the heavy machinery, steel, automotive, medical equipment, chemical, footwear, textile and electronics industries.', '250 despachos aduanales al mes', '250 customs clearances a month', null, 'sin_dato', null, null, array['Despacho aduanal de importación y exportación', 'Flete marítimo: FCL, LCL, refrigerado y carga de proyecto', 'Flete terrestre con rastreo GPS y custodia', 'Almacenaje, consolidación y desconsolidación', 'Recinto Fiscalizado Estratégico (RFE) y depósito fiscal', 'Oficina IMMEX', 'Certificación de IVA e IEPS', 'Clasificación arancelaria y control de permisos', 'Seguro de mercancías', 'Mercancía peligrosa y carga sobredimensionada']::text[], '{}'::integer[], 'rcareaga@grupoamp.mx', '+52 314 146 2708', 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('grupo-ravara', 'Grupo RAVARA', null, 'nuevo-leon', 'García', 'cosmetica', 'Centro tecnológico que diseña y fabrica ingredientes activos para cosmética y cuidado personal.', 'Technology centre that designs and manufactures active ingredients for cosmetics and personal care.', 'Grupo RAVARA es un centro tecnológico mexicano que diseña y manufactura ingredientes activos para las industrias cosmética, de cuidado personal, del hogar y capilar. Combina ciencia y herbolaria tradicional para desarrollar extractos botánicos, proteínas, péptidos y complejos activos con funciones de hidratación, antienvejecimiento, protección capilar, regeneración celular, control antimicrobiano y protección contra la contaminación.', 'Grupo RAVARA is a Mexican technology centre that designs and manufactures active ingredients for the cosmetics, personal care, home care and hair care industries. It combines science with traditional herbal knowledge to develop botanical extracts, proteins, peptides and active complexes for hydration, anti-ageing, hair protection, cell renewal, antimicrobial control and protection against pollution.', 'Ingredientes de origen natural', 'Naturally derived ingredients', null, 'sin_dato', null, null, array['Extractos botánicos', 'Proteínas y péptidos', 'Complejos activos', 'Activos para cuidado capilar', 'Formulaciones a la medida']::text[], '{}'::integer[], 'alejandra@gruporavara.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('lari-moda', 'LARI MODA', null, 'oaxaca', null, 'textil-y-confeccion', 'Prendas bordadas a mano por mujeres artesanas, con telas y procesos conscientes.', 'Garments hand-embroidered by women artisans, using mindful fabrics and processes.', 'LARI MODA crea prendas bordadas a mano por mujeres artesanas en pequeños talleres comunitarios, con telas más amigables con la naturaleza. Su modelo impulsa el empoderamiento económico de las mujeres, preserva técnicas tradicionales de bordado y promueve una moda ética, con piezas atemporales pensadas para durar.', 'LARI MODA makes garments hand-embroidered by women artisans in small community workshops, using more environmentally friendly fabrics. Its model supports women''s economic empowerment, preserves traditional embroidery techniques and promotes ethical fashion, with timeless pieces made to last.', 'Bordado artesanal', 'Hand embroidery', null, 'sin_dato', null, null, array['Prendas bordadas a mano', 'Moda sostenible']::text[], '{}'::integer[], 'oly@larimoda.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('licorera-del-sur', 'Licorera del Sur', null, 'oaxaca', 'Santiago Matatlán', 'bebidas-espirituosas', 'Productora y distribuidora de bebidas espirituosas de Santiago Matatlán, Oaxaca, con más de 40 años de experiencia.', 'Spirits producer and distributor from Santiago Matatlán, Oaxaca, with more than 40 years of experience.', 'Licorera del Sur produce y distribuye bebidas espirituosas desde Santiago Matatlán, Oaxaca, una de las regiones con mayor tradición mezcalera del país. Con más de 40 años de experiencia y productos galardonados, cuenta con capacidad propia de fabricación, embotellado, etiquetado y distribución.', 'Licorera del Sur produces and distributes spirits from Santiago Matatlán, Oaxaca, one of Mexico''s most traditional mezcal regions. With more than 40 years of experience and award-winning products, it has its own production, bottling, labelling and distribution capacity.', '40 años de trayectoria', '40 years in business', null, 'sin_dato', null, null, array['Bebidas espirituosas']::text[], '{}'::integer[], 'jrodriguez@licoreradelsur.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('mezcal-capotlan', 'Mezcal Capotlán', null, 'oaxaca', 'Las Razas', 'destilados-de-agave', 'Mezcal artesanal oaxaqueño de agaves Espadín, Tobalá y Tepeztate.', 'Artisanal mezcal from Oaxaca made from Espadín, Tobalá and Tepeztate agaves.', 'Mezcal Capotlán elabora y promueve mezcal artesanal de alta calidad con métodos tradicionales de producción. Sus destilados expresan el carácter de cada variedad de agave —Espadín, Tobalá y Tepeztate— y la riqueza cultural, los aromas y sabores de Oaxaca.', 'Mezcal Capotlán makes and promotes high-quality artisanal mezcal using traditional production methods. Its spirits express the character of each agave variety — Espadín, Tobalá and Tepeztate — and the cultural richness, aromas and flavours of Oaxaca.', 'Mezcal artesanal', 'Artisanal mezcal', null, 'sin_dato', null, null, array['Espadín', 'Tobalá', 'Tepeztate']::text[], '{}'::integer[], 'mezcalcapotlan@gmail.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('mezcal-dolores', 'Mezcal Dolores', null, 'oaxaca', 'Santiago Matatlán', 'destilados-de-agave', 'Mezcal artesanal de Santiago Matatlán elaborado con procesos tradicionales.', 'Artisanal mezcal from Santiago Matatlán made with traditional processes.', 'Mezcal Dolores produce y comercializa mezcal artesanal cuidando cada etapa del proceso tradicional, para ofrecer destilados auténticos, con identidad y carácter propio, dirigidos al mercado nacional e internacional.', 'Mezcal Dolores produces and sells artisanal mezcal, taking care of every stage of the traditional process to offer authentic spirits with their own identity and character for domestic and international markets.', 'Mezcal artesanal', 'Artisanal mezcal', null, 'sin_dato', null, null, array['Mezcal artesanal']::text[], '{}'::integer[], 'marilyn.dolores30@gmail.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('mezcal-la-entrega', 'Mezcal La Entrega', null, 'oaxaca', 'Oaxaca de Juárez', 'destilados-de-agave', 'Mezcal artesanal 100% orgánico, destilado en alambique de cobre.', '100% organic artisanal mezcal distilled in copper stills.', 'Mezcal La Entrega produce mezcal artesanal 100% orgánico con procesos tradicionales: agaves maduros cocidos en hornos de piedra subterráneos, fermentación natural en tinas de madera y destilación en alambique de cobre. El resultado es un destilado puro, complejo y con el ahumado característico del mezcal.', 'Mezcal La Entrega produces 100% organic artisanal mezcal using traditional methods: mature agaves cooked in underground stone ovens, natural fermentation in wooden vats and distillation in copper stills. The result is a pure, complex spirit with mezcal''s characteristic smokiness.', '100% orgánico', '100% organic', null, 'sin_dato', null, null, array['Mezcal artesanal orgánico']::text[], '{}'::integer[], 'laentregamezcal@gmail.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('multilog-internacional', 'Multilog Internacional', null, 'ciudad-de-mexico', null, 'logistica-comercio-exterior', 'Logística y cadena de suministro: transporte terrestre, aéreo y marítimo, almacenaje y distribución.', 'Logistics and supply chain: road, air and sea freight, warehousing and distribution.', 'Multilog Internacional ofrece desde hace más de 16 años soluciones integrales de logística y cadena de suministro para empresas de distintos sectores. Integra transporte terrestre, aéreo y marítimo, almacenamiento, distribución y operaciones in-house bajo un mismo esquema, con atención personalizada.', 'For more than 16 years, Multilog Internacional has provided end-to-end logistics and supply chain solutions for companies in different sectors. It combines road, air and sea freight, warehousing, distribution and in-house operations under a single scheme, with personalised service.', '16 años en logística', '16 years in logistics', null, 'sin_dato', null, null, array['Transporte terrestre', 'Transporte aéreo', 'Transporte marítimo', 'Almacenamiento', 'Distribución', 'Operaciones in-house']::text[], '{}'::integer[], 'orlando.vazquez@multilog.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('oceamar', 'Oceamar', null, 'campeche', 'Ciudad del Carmen', 'logistica-comercio-exterior', 'Agencia de logística offshore para la industria marítima y petrolera.', 'Offshore logistics agency for the maritime and oil industries.', 'Oceamar (Ocean Marine) es una agencia de logística integral offshore que atiende a la industria marítima y petrolera. Coordina soluciones logísticas, operativas y de soporte para operaciones costa afuera, con foco en eficiencia, seguridad y cumplimiento en proyectos del sector energético.', 'Oceamar (Ocean Marine) is an end-to-end offshore logistics agency serving the maritime and oil industries. It coordinates logistics, operational and support solutions for offshore operations, focusing on efficiency, safety and compliance in energy sector projects.', 'Logística offshore', 'Offshore logistics', null, 'sin_dato', null, null, array['Logística offshore', 'Soporte a operaciones costa afuera', 'Servicios a la industria marítima y petrolera']::text[], '{}'::integer[], 'enrique.escobar@oceamar.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('pilu-uniformes', 'Pilu Uniformes', null, 'puebla', 'Puebla', 'textil-y-confeccion', 'Diseño y fabricación de uniformes industriales e institucionales.', 'Design and manufacture of industrial and corporate uniforms.', 'Pilu Uniformes Industriales de México diseña, fabrica y comercializa uniformes industriales e institucionales adaptados a cada organización. Combina imagen corporativa, ergonomía y seguridad en prendas funcionales y de alta calidad.', 'Pilu Uniformes Industriales de México designs, manufactures and sells industrial and corporate uniforms tailored to each organisation. It combines corporate image, ergonomics and safety in functional, high-quality garments.', 'Uniformes a la medida', 'Made-to-order uniforms', null, 'sin_dato', null, null, array['Uniformes industriales', 'Uniformes institucionales']::text[], '{}'::integer[], 'eduardosanchez@piluniformes.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('las-vegas-premium-limes', 'Las Vegas Premium Limes', 'Productos Men-Frut S.A. de C.V.', 'veracruz', 'Martínez de la Torre', 'frutas-y-hortalizas', 'Empaque y exportación de lima persa de alta calidad durante todo el año.', 'Packing and export of high-quality Persian limes all year round.', 'Productos Men-Frut empaca y exporta lima persa bajo la marca Las Vegas Premium Limes desde Martínez de la Torre, Veracruz, una de las regiones citrícolas más importantes de México. Ofrece producto fresco todo el año y cumple estándares internacionales para abastecer mercados alrededor del mundo.', 'Productos Men-Frut packs and exports Persian limes under the Las Vegas Premium Limes brand from Martínez de la Torre, Veracruz, one of Mexico''s leading citrus regions. It supplies fresh product all year round and meets international standards to serve markets around the world.', 'Lima persa todo el año', 'Persian limes all year round', null, 'exportando', null, null, array['Lima persa']::text[], '{}'::integer[], 'hugo.mendez@citru-mex.com.mx', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('recodding', 'Recodding', null, 'puebla', 'Puebla', 'tecnologia', 'Automatización con agentes de inteligencia artificial para los procesos operativos de las empresas: conciliación, aprobaciones, cotizaciones y reportes.', 'AI agent automation for companies'' operational processes: reconciliation, approvals, quotes and reporting.', 'Recodding construye agentes de automatización a la medida que ejecutan los flujos de trabajo operativos de una empresa —aprobaciones, conciliación de facturas, reportes, cotizaciones, clasificación de solicitudes o el paso de pedidos entre sistemas—: el trabajo que antes se hacía a mano, para que se complete en minutos en lugar de días. Cada agente se diseña para un proceso específico y se conecta a los sistemas que la empresa ya usa.

Su método avanza por etapas: primero mapea el proceso tal como lo ejecuta el equipo; después construye el agente y lo pone a trabajar en paralelo con revisión humana en cada decisión, y solo cuando su precisión se comprueba con volumen real asume el proceso completo, con registro de auditoría y una persona que puede intervenir ante cualquier excepción. Atiende a empresas de servicios financieros, manufactura, logística y cadena de suministro, comercio electrónico, salud, seguros y servicios profesionales.', 'Recodding builds custom automation agents that run a company''s operational workflows — approvals, invoice reconciliation, reporting, quotes, request triage or moving orders between systems: work that used to be done by hand, so it gets done in minutes instead of days. Each agent is designed for a specific process and connects to the systems the company already uses.

Its method works in stages: first it maps the process as the team actually runs it; then it builds the agent and runs it in parallel with human review of every decision, and only once its accuracy is proven on real volume does it take over the whole process, with a full audit trail and a person who can step in on any exception. It serves companies in financial services, manufacturing, logistics and supply chain, e-commerce, healthcare, insurance and professional services.', 'Agentes de IA con supervisión humana', 'AI agents with human oversight', null, 'sin_dato', null, null, array['Agentes de automatización a la medida', 'Conciliación de facturas y cuentas por pagar', 'Flujo de pedidos entre sistemas', 'Cotizaciones y contratos desde el CRM', 'Clasificación y enrutamiento de solicitudes', 'Reportes y datos entre aplicaciones']::text[], '{}'::integer[], 'eduardo@recodding.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('saeta', 'SAETA Orientación Corporativa', null, 'puebla', 'San Andrés Cholula', 'consultoria', 'Consultoría integral para empresas mexicanas y extranjeras: comercio exterior e IMMEX, contabilidad, legal, nómina y softlanding, en español, inglés y alemán.', 'All-in-one consulting for Mexican and foreign companies: foreign trade and IMMEX, accounting, legal, payroll and soft landing, in Spanish, English and German.', 'SAETA Orientación Corporativa es una firma de consultoría que reúne bajo un mismo techo siete áreas de servicio —softlanding, legal, contabilidad, fiscal, nómina y tesorería, comercio exterior y auditoría— para descomplicar los procesos corporativos de sus clientes. Fundada en 2022, atiende a más de 60 empresas nacionales e internacionales desde sus oficinas en Puebla y en el German Centre de la Ciudad de México.

En comercio exterior acompaña a las empresas en el programa IMMEX, el cumplimiento de NOMs y permisos de COFEPRIS y SEDENA, auditorías con Data Stage y de los Anexos 24 y 30, reglas de origen, devolución de IVA y la coordinación de la logística y el despacho aduanal. Trabaja en español, inglés y alemán, y acompaña a empresas extranjeras, incluidas las de habla alemana, en su llegada a México.', 'SAETA Orientación Corporativa is a consulting firm that brings seven service areas under one roof — soft landing, legal, accounting, tax, payroll and treasury, foreign trade and auditing — to simplify its clients'' corporate processes. Founded in 2022, it serves more than 60 Mexican and international companies from its offices in Puebla and at the German Centre in Mexico City.

In foreign trade, it supports companies with the IMMEX programme, compliance with Mexican Official Standards (NOMs) and COFEPRIS and SEDENA permits, Data Stage audits and Annex 24 and 30 reviews, rules of origin, VAT refunds, and coordination of logistics and customs clearance. It works in Spanish, English and German, and helps foreign companies, including German-speaking ones, set up in Mexico.', 'Atiende en español, inglés y alemán', 'Service in Spanish, English and German', 2022, 'sin_dato', null, null, array['Softlanding para empresas extranjeras', 'Programa IMMEX', 'NOMs y permisos COFEPRIS y SEDENA', 'Auditoría de comercio exterior (Data Stage, Anexos 24 y 30)', 'Consultoría aduanera y reglas de origen', 'Coordinación logística y aduanal', 'Contabilidad, controlling y fiscal', 'Nómina y tesorería', 'Derecho corporativo, laboral y mercantil', 'Trámites migratorios', 'Registro de marcas']::text[], '{}'::integer[], 'eduardo.lopez@saetaoc.com', '+52 222 533 9586', 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('solferino-native', 'Solferino Native', null, 'quintana-roo', 'Solferino', 'bebidas-espirituosas', 'Primera destilería de Quintana Roo: gin artesanal con botánicos de la selva maya, medalla de oro como Mejor Gin de México en los World Gin Awards 2025.', 'Quintana Roo''s first distillery: craft gin with Mayan jungle botanicals, awarded gold as Best Mexican Gin at the World Gin Awards 2025.', 'Solferino Native es la primera destilería de Quintana Roo. Nació en 2020 en Solferino, un poblado de la selva maya camino a Holbox, y elabora gin y licores artesanales en alambique de cobre, en microlotes de máximo 120 botellas. Sus botánicos —zacate limón, hierbabuena, hoja santa, pimienta negra, romero y piel de toronja— se recolectan frescos con los vecinos del pueblo y se suman al enebro, el regaliz y la canela, sin químicos ni conservadores.

Su Dry Gin ganó la medalla de oro como Mejor Gin de México en los World Gin Awards 2025, en Reino Unido, donde quedó entre los seis mejores del mundo en la categoría Contemporary Style, y volvió a ser reconocido en la edición 2026. Suma oro en Cata d''Or World Spirits Awards (Chile, 2021 y 2025), plata en Las Vegas Global Spirit Awards 2025 y Gran Oro en el Concurso de Espirituosos de Guanajuato, y es miembro de The Gin Guild de Londres. Se vende en Quintana Roo, Ciudad de México, Estado de México, Querétaro y Baja California, en las tiendas La Europea de todo el país y en Amazon y Mercado Libre.', 'Solferino Native is Quintana Roo''s first distillery. It was founded in 2020 in Solferino, a village in the Mayan jungle on the way to Holbox, and makes craft gin and liqueurs in copper stills, in micro-batches of no more than 120 bottles. Its botanicals — lemongrass, spearmint, hoja santa, black pepper, rosemary and grapefruit peel — are gathered fresh with local villagers and added to juniper, liquorice and cinnamon, with no chemicals or preservatives.

Its Dry Gin won gold as Best Mexican Gin at the World Gin Awards 2025 in the United Kingdom, where it ranked among the world''s top six in the Contemporary Style category, and was recognised again in the 2026 edition. It also holds gold at the Cata d''Or World Spirits Awards (Chile, 2021 and 2025), silver at the Las Vegas Global Spirit Awards 2025 and Grand Gold at the Guanajuato Spirits Competition, and is a member of The Gin Guild in London. It is sold in Quintana Roo, Mexico City, the State of Mexico, Querétaro and Baja California, in La Europea stores nationwide, and on Amazon and Mercado Libre.', 'Oro · World Gin Awards 2025', 'Gold · World Gin Awards 2025', null, 'sin_dato', null, '30–55%', array['Solferino Native Dry Gin · 40% Alc. · 750 ml', 'Solferino Native Overproof Edition · gin 55% Alc.', 'Solferino Native Flair Edition · gin para bartenders de flair', 'Solferino Native Absenta · 55% Alc.', 'Balam · licor cítrico de zacate limón, naranja y toronja', 'Pancheel · licor de yaka · 30% Alc.']::text[], array[750]::integer[], 'info@solferinogin.com', null, 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, exporta_desde, situacion, maquila, abv, productos, presentaciones_ml, contacto_email, contacto_tel, estatus, fuente)
values ('toke-innova', 'Toke Innova', null, 'puebla', 'Puebla', 'alimentos-procesados', 'Salsa macha, chimichurri, especias y productos artesanales de Puebla, 100% naturales, con venta en 12 estados de México y cuatro de Estados Unidos.', 'Artisanal salsa macha, chimichurri, spices and pantry products from Puebla — 100% natural, sold in 12 Mexican states and four US states.', 'Toke Innova, fundada en Puebla en 2017, elabora productos artesanales mexicanos 100% naturales bajo sus marcas La Artesanal Herencia Orza® y ¡Ay Buey!®. Empezó con su Salsa Macha y hoy su catálogo reúne 24 presentaciones: salsa macha en cuatro variedades, chimichurri, chiles y especias, miel, perlas de tapioca, crema de cacahuate y galletas.

Vende en 12 estados de México y en Estados Unidos, donde tiene presencia en California, Kansas, Oklahoma y Texas; sus etiquetas ya vienen en inglés y francés. Cuenta con registro ante COFEPRIS y la FDA. Sus productos tienen una vida de anaquel de 6 meses a 3 años y se surten en cajas de 8 a 52 piezas, según la presentación.', 'Toke Innova, founded in Puebla in 2017, makes 100% natural artisanal Mexican products under its La Artesanal Herencia Orza® and ¡Ay Buey!® brands. It started with its Salsa Macha and its catalogue now includes 24 products: salsa macha in four varieties, chimichurri, chillies and spices, honey, tapioca pearls, peanut butter and cookies.

It sells in 12 Mexican states and in the United States, with presence in California, Kansas, Oklahoma and Texas, and its labels are already in English and French. It is registered with COFEPRIS and the FDA. Shelf life ranges from 6 months to 3 years, and products ship in cases of 8 to 52 units depending on the item.', 'Vende en 4 estados de EUA', 'Sold in 4 US states', null, 'exportando', null, null, array['Salsa Macha 4 chiles y 6 semillas · 200 g', 'Salsa Macha 3 chiles y 3 semillas · 80 g', 'Salsa Macha de cacahuate con chile morita · 200 g y 80 g', 'Salsa Macha de miel de abeja y arándanos · 200 g y 80 g', 'Salsa No Tan Macha · 200 g y 80 g', 'Chimichurri · 200 g y 80 g', 'Chimichurri picoso · 80 g', 'Chile quebrado · 150 g', 'Pimienta de cayena · 60 g', 'Paprika · 60 g', 'Ajonjolí negro · 75 g', 'Miel pura de abeja · 100 g', 'Perlas de miel con propóleo · 80 g', 'Perlas de tapioca · 250 g y 500 g', 'Crema de cacahuate · 340 g', 'Galletas artesanales (nuez con amaranto, arándanos, avena, avellana) · 100 g']::text[], '{}'::integer[], 'aortiz.ventas@tokeinnova.com', '+52 222 801 7636', 'borrador', 'Directorio de Socios COMCE Sur 2026')
on conflict (slug) do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'toke-innova' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'toke-innova' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'cofepris' from empresas where slug = 'toke-innova' on conflict do nothing;

-- Después de revisarlas en el panel, para publicar todas de una vez:
-- update empresas set estatus = 'publicado' where fuente = 'Directorio de Socios COMCE Sur 2026' and estatus = 'borrador';
