-- Sur Exporta — carga inicial de datos (generado por supabase/build-seed.js)
-- Ejecutar en Supabase → SQL Editor. Es idempotente: se puede volver a correr.
begin;

-- Estados
insert into estados (clave, nombre) values ('oaxaca', 'Oaxaca') on conflict (clave) do update set nombre = excluded.nombre;

-- Sectores
insert into sectores (clave, nombre_es, nombre_en, hs_partida, fraccion_mx, fraccion_validada) values ('destilados-de-agave', 'Destilados de agave', 'Agave spirits', '22.08', '2208.90.03', false) on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;

-- Países de destino
insert into paises (clave, nombre_es, nombre_en) values ('estados-unidos', 'Estados Unidos', 'United States') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('canada', 'Canadá', 'Canada') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('japon', 'Japón', 'Japan') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('suiza', 'Suiza', 'Switzerland') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('rusia', 'Rusia', 'Russia') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('alemania', 'Alemania', 'Germany') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('australia', 'Australia', 'Australia') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('suecia', 'Suecia', 'Sweden') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('italia', 'Italia', 'Italy') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('reino-unido', 'Reino Unido', 'United Kingdom') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('china', 'China', 'China') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('espana', 'España', 'Spain') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('polonia', 'Polonia', 'Poland') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('francia', 'Francia', 'France') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('singapur', 'Singapur', 'Singapore') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('paises-bajos', 'Países Bajos', 'Netherlands') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into paises (clave, nombre_es, nombre_en) values ('hong-kong', 'Hong Kong', 'Hong Kong') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;

-- Certificaciones
insert into certificaciones (clave, nombre_es, nombre_en) values ('comercam', 'COMERCAM', 'COMERCAM') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('nom-070-scfi-2016', 'NOM-070-SCFI-2016', 'NOM-070-SCFI-2016') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('certificado-de-origen', 'Certificado de Origen', 'Certificate of Origin') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('fda', 'FDA', 'FDA') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('ttb', 'TTB', 'TTB') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('libre-venta-cofepris', 'Libre Venta COFEPRIS', 'COFEPRIS Free Sale') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('v-label', 'V-Label', 'V-Label') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('kosher', 'Kosher', 'Kosher') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('amma', 'AMMA', 'AMMA') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;
insert into certificaciones (clave, nombre_es, nombre_en) values ('cidam', 'CIDAM', 'CIDAM') on conflict (clave) do update set nombre_es = excluded.nombre_es, nombre_en = excluded.nombre_en;

-- Empresas
insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-carreno', 'Mezcal Carreño', 'Mezcal Carreño S.A. de C.V.', 'oaxaca', 'San Dionisio Ocotlán', 'destilados-de-agave', 'Casa familiar de San Dionisio Ocotlán con el registro sanitario más completo del directorio y ocho años exportando a seis mercados.', 'Family house in San Dionisio Ocotlán with the most complete regulatory record in the directory and eight years shipping to six markets.', 'Detrás de cada copa de Mezcal Carreño hay una historia de resistencia cultural, de defensa de una bebida ancestral, de cuidado por el campo y conservación de la tierra, de solidaridad con el maestro mezcalero y, sobre todo, de pasión familiar. La casa opera con registro vigente ante COMERCAM y suma siete certificaciones internacionales, incluida V-Label, la única en todo el directorio.', 'Behind every glass of Mezcal Carreño lies a story of cultural resilience, of defending an ancestral spirit, of caring for the land, of solidarity with the master mezcalero and, above all, of family passion. The house holds an active COMERCAM registration and carries seven international certifications, including V-Label — the only one in the directory.', 'Única con certificación V-Label', 'Only listing with V-Label certification', 9000, 80, 7200, 2015, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '45–46%', array['Espadín', 'Tobalá', 'Cuishe', 'Tepeztate', 'Tobasiche', 'Ensamble 7'], array[750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-carreno.webp', 'https://www.sur-exporta.com/foto-mezcal-carreno.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-bendito-remedio', 'Mezcal Bendito Remedio', 'Eberth Daniel Vera Canseco', 'oaxaca', 'San Juan Guelavía', 'destilados-de-agave', 'Once variedades de agave y ocho presentaciones, de la muestra de 100 ml a la garrafa de 4 litros. Australia es su mercado principal.', 'Eleven agave varieties and eight formats, from a 100 ml sample to a 4-litre carboy. Australia is its main market.', 'Una empresa que quiere llevar lo mejor de Oaxaca y de México al mundo, y que busca activamente socios comerciales para mejorar el producto en el mercado local, nacional y global. Su catálogo es de los más amplios del directorio en variedades de agave: once en total, incluidos Jabalí, Coyote, Sierra Negra y Cirial. Exporta 7,000 de los 10,000 litros que produce cada mes.', 'A company set on taking the best of Oaxaca and Mexico to the world, and actively seeking trade partners to improve its product locally, nationally and globally. Its range is among the broadest in the directory: eleven agave varieties, including Jabalí, Coyote, Sierra Negra and Cirial. It exports 7,000 of the 10,000 litres it produces each month.', '8 presentaciones, de 100 ml a 4 L', '8 formats, from 100 ml to 4 L', 10000, 70, 7000, 2020, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, false, '38–50%', array['Espadín', 'Tobalá', 'Tobalá destilado con piña', 'Arroqueño', 'Jabalí', 'Coyote', 'Sierra Negra', 'Cirial', 'Barril', 'Madre Cuishe', 'Tepeztate'], array[100, 200, 250, 500, 700, 750, 1000, 4000]::integer[], 'https://www.sur-exporta.com/logo-mezcal-bendito-remedio.webp', 'https://www.sur-exporta.com/foto-mezcal-bendito-remedio.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-don-galo', 'Mezcal Don Galo', 'Comercializadora AROMZIUR S.A. de C.V.', 'oaxaca', 'San Juan del Río, Tlacolula', 'destilados-de-agave', 'Seis mercados en tres continentes —de Suecia a China— con el 60% de su producción destinada a la exportación.', 'Six markets across three continents — from Sweden to China — with 60% of output going to export.', 'Elaborado con agave Espadín (Angustifolia Haw), fruto de un proceso ancestral guiado por familias con saberes centenarios. La preparación de la tierra, la siembra en suelo árido y la cosecha son rituales enraizados en la conexión entre la tierra y el hombre, con una madurez que se alcanza a los seis u ocho años. Es una de las casas más diversificadas del directorio: seis destinos abiertos en América, Europa y Asia.', 'Made from Espadín agave (Angustifolia Haw), the product of an ancestral process guided by families with centuries-old knowledge. Preparing the soil, planting in arid ground and harvesting are rituals rooted in the bond between land and people, with maturity reached at six to eight years. It is one of the most diversified houses in the directory, with six destinations open across the Americas, Europe and Asia.', '6 mercados en tres continentes', '6 markets across three continents', 5000, 60, 3000, 2020, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '45–48%', array['Espadín', 'Cuishe', 'Tobalá', 'Joven', 'Añejo'], array[750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-don-galo.webp', 'https://www.sur-exporta.com/foto-mezcal-don-galo.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-altares-de-mi-tierra', 'Mezcal Altares de mi Tierra', 'Cristal Dalila Santiago Andrade', 'oaxaca', 'San Dionisio Ocotepec', 'destilados-de-agave', 'Empresa dirigida por una mujer oaxaqueña, con destilados de autor en chocolate, frutos rojos y cempasúchil. Exporta a Japón.', 'A woman-led Oaxacan company with signature distillates in cacao, red berries and marigold. Currently exporting to Japan.', 'Empresa 100% oaxaqueña que elabora mezcal con maguey Espadín cultivado en Miahuatlán. Satisface los paladares más exigentes y cumple con los estándares más altos de calidad sin perder la autenticidad del producto. Su diferenciador está en los destilados de autor —chocolate, frutos rojos y cempasúchil—, una línea que abre mercados de especialidad en Asia y Oceanía.', 'A wholly Oaxacan company producing mezcal from Espadín agave grown in Miahuatlán. It satisfies the most demanding palates and meets the highest quality standards without losing the product''s authenticity. Its edge lies in signature distillates — cacao, red berries and marigold — a line that opens speciality markets across Asia and Oceania.', 'Destilados con chocolate, frutos rojos y cempasúchil', 'Distilled with cacao, red berries and marigold', 5000, 20, 1000, 2021, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '45–47%', array['Espadín', 'Espadín destilado con chocolate', 'Espadín destilado con frutos rojos', 'Espadín destilado con cempasúchil', 'Tobalá'], array[50, 375, 750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-altares-de-mi-tierra.webp', 'https://www.sur-exporta.com/foto-mezcal-altares-de-mi-tierra.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-casa-parada', 'Mezcal Casa Parada', 'Agrícola Hermanos Parada Ruíz S.A. de C.V.', 'oaxaca', 'San Carlos Yautepec', 'destilados-de-agave', 'Sesenta años de oficio en San Carlos Yautepec, certificación Kosher y 5,000 litros mensuales colocados en Europa y Canadá.', 'Sixty years of craft in San Carlos Yautepec, Kosher certification and 5,000 litres a month placed in Europe and Canada.', 'Empresa 100% oaxaqueña con más de sesenta años de experiencia. Ha sido primordial para la casa ser promotora de una consigna heredada de sus antecesores: respetar el campo y conservar la diversidad del agave, continuando su evolución y agradeciendo a la tierra que les da origen e identidad. Su portafolio incluye un destilado de mango y cinco variedades de agave, con certificación Kosher para mercados de especialidad.', 'A wholly Oaxacan company with more than sixty years of experience. Central to the house is a principle inherited from its forebears: respect the land and preserve agave diversity, continuing its evolution and giving thanks to the soil that gives them origin and identity. Its range includes a mango distillate and five agave varieties, with Kosher certification for speciality markets.', '60 años de oficio · Kosher', '60 years of craft · Kosher', 9000, 60, 5000, 2022, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '40–45%', array['Espadín Joven', 'Espadín Reposado', 'Tobalá', 'Cuishe', 'Tepeztate', 'Destilado de mango'], array[250, 375, 700, 750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-casa-parada.webp', 'https://www.sur-exporta.com/foto-mezcal-casa-parada.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-convite', 'Mezcal Convite', 'Destilería Convite S.A. de C.V.', 'oaxaca', 'San Baltazar Guelavila', 'destilados-de-agave', 'El portafolio más amplio del directorio: diez productos, incluidos pechuga de pavo y ensamble silvestre de cinco agaves.', 'The widest range in the directory: ten products, including turkey-breast pechuga and a five-agave wild blend.', 'Empresa 100% oaxaqueña que custodia tradiciones destilatorias centenarias. Su compromiso con la calidad y la sustentabilidad ambiental se refleja en cada sorbo de su mezcal artesanal. Apoya el comercio justo y el desarrollo de la comunidad, realizando todas sus actividades en Oaxaca. Con 10,000 litros mensuales de capacidad y un solo mercado abierto, es la casa con mayor margen de crecimiento del directorio.', 'A wholly Oaxacan company safeguarding centuries-old distilling traditions. Its commitment to quality and environmental sustainability shows in every sip of its artisanal mezcal. It supports fair trade and community development, carrying out all its operations in Oaxaca. With 10,000 litres of monthly capacity and a single market open, it is the house with the greatest room to grow in the directory.', '10 productos: el portafolio más amplio', '10 products: the widest portfolio', 10000, 21, 2100, 2017, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '38–46%', array['Espadín', 'Cuishe', 'Madre Cuishe', 'Tobalá', 'Espadín destilado con pechuga de pavo', 'Ensamble Silvestre 5 Agaves', 'Tepeztate', 'Coyote', 'Jabalí', 'Espadín abocado con grana cochinilla'], array[700, 750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-convite.webp', 'https://www.sur-exporta.com/foto-mezcal-convite.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-elixir-de-agave', 'Mezcal Elixir de Agave', 'Elixir de Agave S.A. de C.V.', 'oaxaca', 'San Dionisio Ocotlán', 'destilados-de-agave', 'Molino egipcio de tracción animal y el 70% de su producción colocada en seis mercados de América, Europa y Asia.', 'An animal-drawn Egyptian mill and 70% of output placed across six markets in the Americas, Europe and Asia.', 'Empresa oaxaqueña con once años de experiencia que produce mezcal artesanal 100% de agave, elaborado en molinos artesanales tipo egipcio con una gran piedra circular de tracción animal y tinajas de madera donde fermenta de forma natural, hasta obtener un alcohol homogéneo y de alta calidad. Su misión es proteger la sustentabilidad y la tradición que enmarcan el producto desde su elaboración hasta su consumo.', 'An Oaxacan company with eleven years of experience producing artisanal 100% agave mezcal, made in Egyptian-style mills with a large animal-drawn circular stone and wooden vats where it ferments naturally, yielding a homogeneous, high-quality spirit. Its mission is to protect the sustainability and tradition that frame the product from production through to consumption.', '6 mercados activos · Kosher', '6 active markets · Kosher', 3500, 70, 2450, 2018, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '41%', array['Espadín', 'Ensamble Tobalá-Espadín', 'Espadín destilado con mandarina y plátano'], array[50, 250, 750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-elixir-de-agave.webp', 'https://www.sur-exporta.com/foto-mezcal-elixir-de-agave.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-los-danzantes', 'Mezcal Los Danzantes', 'Destilería Los Danzantes S.A. de C.V.', 'oaxaca', 'Santiago Matatlán', 'destilados-de-agave', 'La trayectoria exportadora más larga del directorio: veinte años colocando mezcal artesanal en Estados Unidos y Europa.', 'The longest export record in the directory: twenty years placing artisanal mezcal in the United States and Europe.', 'Empresa 100% oaxaqueña con veinte años de experiencia. Destilería Los Danzantes, lugar protegido por los espíritus danzantes, es testigo de la producción de mezcal artesanal desde la plantación y el corte de los agaves hasta la destilación en alambiques de cobre. Cada botella resguarda una tradición antigua, conserva el espíritu de la tierra que vio crecer la planta y el saber ancestral de cada productor.', 'A wholly Oaxacan company with twenty years of experience. Destilería Los Danzantes, a place watched over by the dancing spirits, witnesses the making of artisanal mezcal from planting and harvesting the agave through to distillation in copper stills. Every bottle holds an old tradition, preserving the spirit of the land that grew the plant and the ancestral knowledge of each producer.', 'Exporta desde 2002', 'Exporting since 2002', 3000, 50, 1500, 2002, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '43–48%', array['Espadín Joven', 'Espadín Reposado', 'Espadín Añejo', 'Tobalá', 'Arroqueño', 'Coyote', 'Sierra Negra'], array[700, 750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-los-danzantes.webp', 'https://www.sur-exporta.com/foto-mezcal-los-danzantes.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-trascendente', 'Mezcal Trascendente', '14 Agaves S.A. de C.V.', 'oaxaca', 'Tlacolula de Matamoros', 'destilados-de-agave', 'Único del directorio que llega a Singapur. Cuatro mercados abiertos con solo el 10% de su capacidad comprometida.', 'The only listing reaching Singapore. Four markets open with just 10% of its capacity committed.', 'Empresa con más de diez años de experiencia que muestra en su sabor magueyes con alto contenido de azúcares naturales, provenientes de comunidades magueyeras nativas del valle central de Oaxaca. Su mapa de destinos es el más inusual del directorio: junto a Estados Unidos y Canadá, ha abierto Singapur y Australia, dos mercados de alto valor y baja competencia para el mezcal mexicano.', 'A company with more than ten years of experience whose flavour comes from agaves rich in natural sugars, sourced from native maguey-growing communities in Oaxaca''s central valley. Its destination map is the most unusual in the directory: alongside the United States and Canada it has opened Singapore and Australia, two high-value, low-competition markets for Mexican mezcal.', 'Único que exporta a Singapur', 'Only listing shipping to Singapore', 6000, 10, 600, 2021, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '35–42%', array['Espadín', 'Ensamble', 'Abocado'], array[750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-trascendente.webp', 'https://www.sur-exporta.com/foto-mezcal-trascendente.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

insert into empresas (slug, marca, razon_social, estado, municipio, sector, resumen_es, resumen_en, descripcion_es, descripcion_en, destacado_es, destacado_en, capacidad_mensual_l, porcentaje_exportado, capacidad_exportada_l, exporta_desde, situacion, padron, maquila, abv, productos, presentaciones_ml, logo_url, foto_url, estatus, fuente)
values ('mezcal-lyobaa', 'Mezcal Lyobaá', 'La Catrina de Oaxaca S.A. de C.V.', 'oaxaca', 'Tamazulapam del Progreso', 'destilados-de-agave', 'Cinco mercados ya validados en Europa y Asia, y 9,700 de sus 10,000 litros mensuales todavía disponibles.', 'Five markets already validated in Europe and Asia, with 9,700 of its 10,000 monthly litres still available.', 'Empresa joven dedicada a la producción, exportación y comercialización de mezcal y sus derivados, así como de productos del campo, del mar, de la acuicultura, la pesca, la silvicultura, la ganadería y la agricultura. Su caso es el más llamativo del directorio: ya abrió cinco mercados —Alemania, Países Bajos, Hong Kong, Japón y Estados Unidos— pero solo coloca 300 de los 10,000 litros que puede producir cada mes.', 'A young company dedicated to producing, exporting and marketing mezcal and its derivatives, alongside products from farming, fishing, aquaculture, forestry and livestock. Its case is the most striking in the directory: it has already opened five markets — Germany, the Netherlands, Hong Kong, Japan and the United States — yet places only 300 of the 10,000 litres it can produce each month.', '97% de su capacidad disponible', '97% of its capacity available', 10000, 3, 300, 2021, 'exportando'::situacion_exportadora, 'vigente'::estatus_padron, true, '40–42%', array['Espadín', 'Tobalá'], array[750]::integer[], 'https://www.sur-exporta.com/logo-mezcal-lyobaa.webp', 'https://www.sur-exporta.com/foto-mezcal-lyobaa.webp', 'publicado'::estatus_publicacion, 'Catálogo de Oferta Exportable de Mezcal, SEDECO Oaxaca')
on conflict (slug) do update set marca = excluded.marca, razon_social = excluded.razon_social, estado = excluded.estado, municipio = excluded.municipio, sector = excluded.sector, resumen_es = excluded.resumen_es, resumen_en = excluded.resumen_en, descripcion_es = excluded.descripcion_es, descripcion_en = excluded.descripcion_en, destacado_es = excluded.destacado_es, destacado_en = excluded.destacado_en, capacidad_mensual_l = excluded.capacidad_mensual_l, porcentaje_exportado = excluded.porcentaje_exportado, capacidad_exportada_l = excluded.capacidad_exportada_l, exporta_desde = excluded.exporta_desde, situacion = excluded.situacion, padron = excluded.padron, maquila = excluded.maquila, abv = excluded.abv, productos = excluded.productos, presentaciones_ml = excluded.presentaciones_ml, logo_url = excluded.logo_url, foto_url = excluded.foto_url, estatus = excluded.estatus, fuente = excluded.fuente;

-- Mercados de destino por empresa
insert into empresa_mercados (empresa_id, pais) select id, 'canada' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'japon' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'suiza' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'rusia' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'alemania' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'australia' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'canada' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'canada' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'suecia' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'italia' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'reino-unido' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'china' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'japon' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'china' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'australia' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'italia' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'canada' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'espana' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'china' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'italia' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'espana' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'polonia' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'canada' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'italia' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'alemania' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'francia' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'canada' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'singapur' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'australia' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'alemania' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'paises-bajos' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'hong-kong' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'japon' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_mercados (empresa_id, pais) select id, 'estados-unidos' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;

-- Certificaciones por empresa
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'libre-venta-cofepris' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'v-label' from empresas where slug = 'mezcal-carreno' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'amma' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'cidam' from empresas where slug = 'mezcal-bendito-remedio' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-don-galo' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'libre-venta-cofepris' from empresas where slug = 'mezcal-altares-de-mi-tierra' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'kosher' from empresas where slug = 'mezcal-casa-parada' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'kosher' from empresas where slug = 'mezcal-convite' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'kosher' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'libre-venta-cofepris' from empresas where slug = 'mezcal-elixir-de-agave' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'libre-venta-cofepris' from empresas where slug = 'mezcal-los-danzantes' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-trascendente' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'comercam' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'nom-070-scfi-2016' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'certificado-de-origen' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'fda' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;
insert into empresa_certificaciones (empresa_id, certificacion) select id, 'ttb' from empresas where slug = 'mezcal-lyobaa' on conflict do nothing;

commit;

-- Comprobación
select (select count(*) from empresas) as empresas,
       (select count(*) from paises) as paises,
       (select count(*) from certificaciones) as certificaciones,
       (select count(*) from empresa_mercados) as relaciones_mercado,
       (select count(*) from empresa_certificaciones) as relaciones_cert;